
package PaqueteGrfico;

import Datos.Clsperson;
import javax.swing.JOptionPane;
import metodos.Consultar;


public class empleados extends javax.swing.JFrame {

     Consultar met = new Consultar();
     Clsperson modelo = new Clsperson();
     
     
     public empleados() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT
      * modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          txtNombre = new javax.swing.JTextField();
          txtFebrero = new javax.swing.JTextField();
          txtMarzo = new javax.swing.JTextField();
          txtEnero = new javax.swing.JTextField();
          txtCodigo = new javax.swing.JTextField();
          btnGuardar = new javax.swing.JButton();
          btnConsultar = new javax.swing.JButton();
          btnModificar = new javax.swing.JButton();
          btnEliminar = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel1.setBackground(new java.awt.Color(42, 42, 95));
          jPanel1.setForeground(new java.awt.Color(255, 255, 255));

          jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Codigo", "Nombre", "Enero", "Febrero", "Marzo", "Promedio", "Total"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          jScrollPane1.setViewportView(jTable1);

          jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(255, 255, 255));
          jLabel1.setText("Registro de Ventas");

          jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(255, 255, 255));
          jLabel2.setText("Nombre");

          jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
          jLabel3.setForeground(new java.awt.Color(255, 255, 255));
          jLabel3.setText("Enero");

          jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
          jLabel4.setForeground(new java.awt.Color(255, 255, 255));
          jLabel4.setText("Febrero");

          jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
          jLabel5.setForeground(new java.awt.Color(255, 255, 255));
          jLabel5.setText("Marzo");

          jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
          jLabel6.setForeground(new java.awt.Color(255, 255, 255));
          jLabel6.setText("Ingresa el Codigo a Eliminar o Modificar");

          txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
          txtNombre.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtNombreActionPerformed(evt);
               }
          });

          txtFebrero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

          txtMarzo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
          txtMarzo.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtMarzoActionPerformed(evt);
               }
          });

          txtEnero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

          txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

          btnGuardar.setBackground(new java.awt.Color(0, 0, 153));
          btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
          btnGuardar.setText("Guardar");
          btnGuardar.setBorderPainted(false);
          btnGuardar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
               }
          });

          btnConsultar.setBackground(new java.awt.Color(0, 0, 153));
          btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
          btnConsultar.setText("Listar");
          btnConsultar.setBorderPainted(false);
          btnConsultar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConsultarActionPerformed(evt);
               }
          });

          btnModificar.setBackground(new java.awt.Color(0, 0, 153));
          btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btnModificar.setForeground(new java.awt.Color(255, 255, 255));
          btnModificar.setText("Modificar");
          btnModificar.setBorderPainted(false);
          btnModificar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnModificarActionPerformed(evt);
               }
          });

          btnEliminar.setBackground(new java.awt.Color(0, 0, 153));
          btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
          btnEliminar.setText("Eliminar");
          btnEliminar.setBorderPainted(false);
          btnEliminar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(77, 77, 77)
                              .addComponent(jLabel1))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(41, 41, 41)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel3)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel5)
                                   .addComponent(txtNombre)
                                   .addComponent(txtEnero)
                                   .addComponent(txtFebrero)
                                   .addComponent(txtMarzo)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addGap(28, 28, 28)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtEnero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jLabel4)
                    .addGap(7, 7, 7)
                    .addComponent(txtFebrero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addComponent(txtMarzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnGuardar)
                         .addComponent(btnConsultar)
                         .addComponent(btnModificar)
                         .addComponent(btnEliminar))
                    .addGap(29, 29, 29)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(57, 57, 57))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtNombreActionPerformed

     private void txtMarzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarzoActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtMarzoActionPerformed

     public void Limpiar(){
          txtNombre.setText(null);
          txtEnero.setText(null);
          txtFebrero.setText(null);
          txtMarzo.setText(null);
          txtCodigo.setText(null);
     }
     
     private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          // TODO add your handling code here:
          
          modelo.setNombre(txtNombre.getText());
          modelo.setEnero(Double.valueOf(txtEnero.getText()));
          modelo.setFebrero(Double.valueOf(txtFebrero.getText()));
          modelo.setMarzo(Double.valueOf(txtMarzo.getText()));
          
          if(met.Registrar(modelo)){
               JOptionPane.showMessageDialog(null, "Los datos se enviaron correctamente");
          }
          Limpiar();
     }//GEN-LAST:event_btnGuardarActionPerformed

     private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
          // TODO add your handling code here:
          met.Consultar(jTable1);
     }//GEN-LAST:event_btnConsultarActionPerformed

     private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
          // TODO add your handling code here:
          modelo.setNombre(txtNombre.getText());
          modelo.setEnero(Double.valueOf(txtEnero.getText()));
          modelo.setFebrero(Double.valueOf(txtFebrero.getText()));
          modelo.setMarzo(Double.valueOf(txtMarzo.getText()));
          modelo.setCodigo(Integer.valueOf(txtCodigo.getText()));
          if(met.Modificar(modelo)){
               JOptionPane.showMessageDialog(null, " Modificacion Correcta");
          }
          Limpiar();
     }//GEN-LAST:event_btnModificarActionPerformed

     private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          // TODO add your handling code here:
           modelo.setCodigo(Integer.valueOf(txtCodigo.getText()));
           if(met.eliminar(modelo)){
                JOptionPane.showMessageDialog(null, "Eliminado");
           }
           Limpiar();
     }//GEN-LAST:event_btnEliminarActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new empleados().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnConsultar;
     private javax.swing.JButton btnEliminar;
     private javax.swing.JButton btnGuardar;
     private javax.swing.JButton btnModificar;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jTable1;
     private javax.swing.JTextField txtCodigo;
     private javax.swing.JTextField txtEnero;
     private javax.swing.JTextField txtFebrero;
     private javax.swing.JTextField txtMarzo;
     private javax.swing.JTextField txtNombre;
     // End of variables declaration//GEN-END:variables
}
